### ISSUE TITLE
Error for install ChatMol plugin

### ISSUE THREAD

**Issue by jiaboli007** [JinyuanSun/ChatMol#4]
I was following the instruction to install chatmol plugin, and got error for module openai not found error: 

load https://raw.githubusercontent.com/JinyuanSun/ChatMol/main/chatmol.py
Traceback (most recent call last):
  File "/private/var/folders/0w/mjyhyf3n4_z2vr3l1d0ps7_w0000gn/T/AppTranslocation/1E319BC0-B882-44AB-B791-34B99CBF7AFC/d/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/parsing.py", line 470, in run
    run_(path, ns_pymol, ns_pymol)
  File "/private/var/folders/0w/mjyhyf3n4_z2vr3l1d0ps7_w0000gn/T/AppTranslocation/1E319BC0-B882-44AB-B791-34B99CBF7AFC/d/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/parsing.py", line 519, in run_file
    execfile(file,global_ns,local_ns)
  File "/private/var/folders/0w/mjyhyf3n4_z2vr3l1d0ps7_w0000gn/T/AppTranslocation/1E319BC0-B882-44AB-B791-34B99CBF7AFC/d/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/parsing.py", line 514, in execfile
    exec(co, global_ns, local_ns)
  File "https://raw.githubusercontent.com/JinyuanSun/ChatMol/main/chatmol.py", line 3, in <module>
    Copyright (c) Schrodinger, Inc.
ModuleNotFoundError: No module named 'openai'

I do installed openai in my default env (python3.9, running python3 and import openai all look good), but the PyMol command shows the module was not found. I am relatively new to use PyMol, so maybe I am missing simple thing simple. Could you show me how to solve the issue? Many thanks.

**Comment by jiaboli007** [comment]
BTW, I also tried the "run" command, and got the same error.

**Comment by JinyuanSun** [comment]
try `pip install openai` in the pymol command line. Seems that your pymol uses different python than your deafult environment. The `run` and `load` not make a difference here.

**Comment by jiaboli007** [comment]
Many thanks, Jinyuan. That solves the problem. 

Any plan to extend the current ChatGPT capability?  From your sample commands, it looks like the current implementation in PyMol is more like a advanced help function to find out how to do things in PyMol. The next step is let ChatGPT to perform a set of actions automatically. For instance. if one type "chatgpt align two proteins 1ake and 4ake", the chatgpt plugin should perform the whole procedure, fetching proteins, align them and display. What do you think about this idea? I am going to hire two summer interns to do something similar for fun. It would be great if we can work together.

**Comment by jiaboli007** [comment]
I just read a blog about your work: https://techserr.com/chatgpt-the-future-of-pymol-automation/

**Comment by jiaboli007** [comment]
I had a closer look at the python code. I saw the option for execute commands that ChatGPT suggested. I will try more cases and see how far we can go.

**Comment by JinyuanSun** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/33344948/234469206-89fa80cc-28d1-4488-864d-1590f47dbc94.png">
Add `True` after the commands, that should work. ;)

**Comment by JinyuanSun** [comment]
The outcome after executing `chatgpt align two proteins 1ake and 4ake, True`:
```
PyMOL>chatgpt align two proteins 1ake and 4ake, True
ChatGPT: To align two proteins in PyMOL, you can use the `align` command. Here's an example code snippet that aligns the two proteins 1AKE and 4AKE:
 
``
# Fetch the two proteins
fetch 1ake
fetch 4ake
 
# Align the two proteins
align 1ake, 4ake
 
# Visualize the aligned proteins
show cartoon
color blue, 1ake
color green, 4ake
``
 
In this code, we first fetch the two proteins using the `fetch` command. Then, we use the `align` command to align the two proteins. Finally, we visualize the aligned proteins using the `show` and `color` commands. The `show` command displays the protein as a cartoon, while the `color` command sets the color of the two proteins to blue and green, respectively.
Executing code: fetch 1ake
PyMOL>fetch 1ake
TITLE     STRUCTURE OF THE COMPLEX BETWEEN ADENYLATE KINASE FROM ESCHERICHIA COLI AND THE INHIBITOR AP5A REFINED AT 1.9 ANGSTROMS RESOLUTION: A MODEL FOR A CATALYTIC TRANSITION STATE
 ExecutiveLoad-Detail: Detected mmCIF
 CmdLoad: "./1ake.cif" loaded as "1ake".
Executing code: fetch 4ake
PyMOL>fetch 4ake
TITLE     ADENYLATE KINASE
 ExecutiveLoad-Detail: Detected mmCIF
 CmdLoad: "./4ake.cif" loaded as "4ake".
Executing code: align 1ake, 4ake
PyMOL>align 1ake, 4ake
 Match: read scoring matrix.
 Match: assigning 808 x 575 pairwise scores.
 MatchAlign: aligning residues (808 vs 575)...
 MatchAlign: score 2180.000
 ExecutiveAlign: 3312 atoms aligned.
 ExecutiveRMS: 7 atoms rejected during cycle 1 (RMSD=18.57).
 ExecutiveRMS: 2 atoms rejected during cycle 2 (RMSD=18.51).
 Executive: RMSD =   18.491 (3303 to 3303 atoms)
Executing code: show cartoon
PyMOL>show cartoon
Executing code: color blue, 1ake
PyMOL>color blue, 1ake
 Executive: Colored 3816 atoms and 1 object.
Executing code: color green, 4ake
PyMOL>color green, 4ake
 Executive: Colored 3459 atoms and 1 object.
Executed code successfully.
```
<img width="846" alt="image" src="https://user-images.githubusercontent.com/33344948/234471453-d6d485cc-c41e-4423-a2a7-c4678f98cbea.png">

**Comment by jiaboli007** [comment]
Yes, I found the magic word 'True'. This is a wonderful starting point. How about we stretch this functionality to do more fancy actions. We can feed ChatGPT a lot of text - actions pairs of the most useful and common tasks behind the scenes. In this allow ChatGPT to exact a set of structured information (actions and their corresponding parameters), and based on this extracted information (in JSON format), and can use PyMol script to perform a sequence of actions behind the scene, so from user perspective, ChatMol is really smart. 

We can continue our discussion, perhaps with email or WeChat. I am living in New York, there is 12 hour time difference between New York and Beijing. My email is jiabo.li@chemxai.com.

**Comment by JinyuanSun** [comment]
Great, hope we have a further discussion soon.
